name: bot
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"


# Dependencies
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  http: 0.12.0
  shared_preferences: 0.4.3
  rxdart: 0.20.0
  bloc: 0.7.4
  flutter_bloc: 0.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
  fonts:
    - family: Veritas
      fonts:
        - asset: assets/fonts/veritas.ttf
